// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohutaeezxljgdrtjyxcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9odXRhZWV6eGxqZ2RydGp5eGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTc0NzAsImV4cCI6MjA3MjM5MzQ3MH0.t6UjWBEFy3eMN1s7HWL47HZ--deVhvNRQmaPUSceyV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});